# Generated by Django 5.1.1 on 2024-09-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ManyToManyField(related_name='items', to='core.supplier'),
        ),
        migrations.DeleteModel(
            name='ItemSupplier',
        ),
    ]
