# Generated by Django 5.1.1 on 2024-09-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_date_added_alter_item_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
