# Generated by Django 5.1.1 on 2024-09-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_item_slug_supplier_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(max_length=100),
        ),
    ]
