# Generated by Django 5.1.1 on 2024-09-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supplier_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
